name: Publish to NPM

on:
    push:
        tags:
            - 'v*'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    contents: read

jobs:
    publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/
                  cache: 'none'

            - name: Generate package-lock.json
              run: npm install --package-lock-only

            - name: Install dependencies
              run: |
                  rm -f package-lock.json
                  npm install --no-shrinkwrap

            - name: Build package
              run: npm run build

            - name: Publish to NPM
              uses: JS-DevTools/npm-publish@v3.1.1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  tag: latest
