name: Node.js CI
# Add & Commit homepage: https://github.com/marketplace/actions/add-commit
# NPM publish homepage: https://github.com/marketplace/actions/npm-publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      # Add built files to the commit as local GitHub user (not the GitHub Actions bot)
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_author: github_actions
          message: "Build files"
          add: "dist"
          commit: --signoff
          push: true

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: latest # or can be set to 'next' for pre-release, or 'beta' for beta release
